"""Persist review results.

`.mentor/state.json` is the single source of truth; `.mentor/DECISIONS.md`
is regenerated from it after every review so the two never drift.
"""

import json
from datetime import date
from pathlib import Path

from mentor.models import Decision

MENTOR_DIR = Path(".mentor")
STATE_FILE = MENTOR_DIR / "state.json"
DECISIONS_FILE = MENTOR_DIR / "DECISIONS.md"

STATUS_LABELS = {
  "owned": "✓ owned",
  "partial": "◐ partial",
  "revisit": "○ to revisit",
  "skipped": "· skipped",
}


def load_state():
  if not STATE_FILE.exists():
    return {"last_reviewed_commit": None, "pending": [], "decisions": {}}
  return json.loads(STATE_FILE.read_text())


def save_state(state):
  MENTOR_DIR.mkdir(exist_ok=True)
  STATE_FILE.write_text(json.dumps(state, indent=2) + "\n")
  DECISIONS_FILE.write_text(render_decisions(state))


def record_result(state, decision, status, answer, scope_label):
  state["decisions"][decision.id] = {
    "decision": decision.model_dump(),
    "status": status,
    "answer": answer,
    "reviewed_at": date.today().isoformat(),
    "scope": scope_label,
  }


def owned_titles(state):
  return [entry["decision"]["title"] for entry in state["decisions"].values() if entry["status"] == "owned"]


def pending_decisions(state):
  return [Decision(**d) for d in state.get("pending", [])]


def render_decisions(state):
  entries = list(state["decisions"].values())
  counts = {status: sum(1 for e in entries if e["status"] == status) for status in STATUS_LABELS}

  lines = [
    "# Design Decisions",
    "",
    "Generated by `mentor review` from `.mentor/state.json`. Each entry is a",
    "design decision found in this codebase, the trade-offs behind it, and",
    "how well it's owned.",
    "",
    " · ".join(f"{STATUS_LABELS[s]}: {n}" for s, n in counts.items() if n) or "No decisions reviewed yet.",
    "",
  ]

  for entry in entries:
    d = entry["decision"]
    lines += [
      f"## {d['title']}",
      f"`{d['location']}` · {d['category']} · {STATUS_LABELS[entry['status']]} ({entry['reviewed_at']})",
      "",
      f"**Chosen:** {d['chosen']}",
      "",
      "**Alternatives:**",
      *[f"- {a}" for a in d["alternatives"]],
      "",
      "**Trade-offs:**",
      *[f"- {c}" for c in d["consequences"]],
      "",
      "**Evidence:** " + ", ".join(f"`{e}`" for e in d["evidence"]),
      "",
    ]
    if entry.get("answer"):
      label = "Your explanation" if entry["status"] == "owned" else "Your last answer"
      lines += [f"**{label}:** \"{entry['answer']}\"", ""]

  return "\n".join(lines)
